-- Üretilen dosya. Kaynak: data/seed/*.json — npm run sync-seed
-- Sahte işveren, ilan, aday YOK.

insert into public.coded_value_translations (kind, code, locale, label) values
  ('system_role','candidate','tr','İş arayan'),
  ('system_role','candidate','en','Candidate'),
  ('system_role','candidate','ru','Соискатель'),
  ('system_role','candidate','he','מועמד'),
  ('system_role','employer','tr','İşveren'),
  ('system_role','employer','en','Employer'),
  ('system_role','employer','ru','Работодатель'),
  ('system_role','employer','he','מעסיק'),
  ('system_role','admin','tr','Yönetici'),
  ('system_role','admin','en','Admin'),
  ('system_role','admin','ru','Админ'),
  ('system_role','admin','he','מנהל'),
  ('org_member_role','owner','tr','Sahip'),
  ('org_member_role','owner','en','Owner'),
  ('org_member_role','owner','ru','Владелец'),
  ('org_member_role','owner','he','בעלים'),
  ('org_member_role','recruiter','tr','İşe alım'),
  ('org_member_role','recruiter','en','Recruiter'),
  ('org_member_role','recruiter','ru','Рекрутер'),
  ('org_member_role','recruiter','he','מגייס'),
  ('org_member_role','viewer','tr','Görüntüleyici'),
  ('org_member_role','viewer','en','Viewer'),
  ('org_member_role','viewer','ru','Наблюдатель'),
  ('org_member_role','viewer','he','צופה'),
  ('remote_type','remote','tr','Uzaktan'),
  ('remote_type','remote','en','Remote'),
  ('remote_type','remote','ru','Удалённо'),
  ('remote_type','remote','he','מרחוק'),
  ('remote_type','hybrid','tr','Hibrit'),
  ('remote_type','hybrid','en','Hybrid'),
  ('remote_type','hybrid','ru','Гибрид'),
  ('remote_type','hybrid','he','היברידי'),
  ('remote_type','onsite','tr','İş yerinde'),
  ('remote_type','onsite','en','On-site'),
  ('remote_type','onsite','ru','В офисе'),
  ('remote_type','onsite','he','במקום'),
  ('remote_type','any','tr','Fark etmez'),
  ('remote_type','any','en','Any'),
  ('remote_type','any','ru','Любой'),
  ('remote_type','any','he','הכל'),
  ('employment_type','FULL_TIME','tr','Tam zamanlı'),
  ('employment_type','FULL_TIME','en','Full time'),
  ('employment_type','FULL_TIME','ru','Полная занятость'),
  ('employment_type','FULL_TIME','he','משרה מלאה'),
  ('employment_type','PART_TIME','tr','Yarı zamanlı'),
  ('employment_type','PART_TIME','en','Part time'),
  ('employment_type','PART_TIME','ru','Частичная занятость'),
  ('employment_type','PART_TIME','he','משרה חלקית'),
  ('employment_type','CONTRACTOR','tr','Sözleşmeli'),
  ('employment_type','CONTRACTOR','en','Contractor'),
  ('employment_type','CONTRACTOR','ru','Подряд'),
  ('employment_type','CONTRACTOR','he','קבלן'),
  ('employment_type','INTERN','tr','Stajyer'),
  ('employment_type','INTERN','en','Intern'),
  ('employment_type','INTERN','ru','Стажёр'),
  ('employment_type','INTERN','he','מתמחה'),
  ('employment_type','TEMPORARY','tr','Geçici'),
  ('employment_type','TEMPORARY','en','Temporary'),
  ('employment_type','TEMPORARY','ru','Временная'),
  ('employment_type','TEMPORARY','he','זמני'),
  ('experience_level','entry','tr','Başlangıç'),
  ('experience_level','entry','en','Entry'),
  ('experience_level','entry','ru','Начальный'),
  ('experience_level','entry','he','מתחיל'),
  ('experience_level','mid','tr','Orta'),
  ('experience_level','mid','en','Mid'),
  ('experience_level','mid','ru','Средний'),
  ('experience_level','mid','he','ביניים'),
  ('experience_level','senior','tr','Kıdemli'),
  ('experience_level','senior','en','Senior'),
  ('experience_level','senior','ru','Старший'),
  ('experience_level','senior','he','בכיר'),
  ('experience_level','lead','tr','Lider'),
  ('experience_level','lead','en','Lead'),
  ('experience_level','lead','ru','Ведущий'),
  ('experience_level','lead','he','ליד'),
  ('job_status','draft','tr','Taslak'),
  ('job_status','draft','en','Draft'),
  ('job_status','draft','ru','Черновик'),
  ('job_status','draft','he','טיוטה'),
  ('job_status','active','tr','Yayında'),
  ('job_status','active','en','Active'),
  ('job_status','active','ru','Активна'),
  ('job_status','active','he','פעיל'),
  ('job_status','expired','tr','Süresi doldu'),
  ('job_status','expired','en','Expired'),
  ('job_status','expired','ru','Истекла'),
  ('job_status','expired','he','פג תוקף'),
  ('job_status','removed','tr','Kaldırıldı'),
  ('job_status','removed','en','Removed'),
  ('job_status','removed','ru','Снята'),
  ('job_status','removed','he','הוסר'),
  ('translation_status','draft','tr','Taslak'),
  ('translation_status','draft','en','Draft'),
  ('translation_status','draft','ru','Черновик'),
  ('translation_status','draft','he','טיוטה'),
  ('translation_status','published','tr','Yayınlandı'),
  ('translation_status','published','en','Published'),
  ('translation_status','published','ru','Опубликовано'),
  ('translation_status','published','he','פורסם'),
  ('application_status','submitted','tr','Gönderildi'),
  ('application_status','submitted','en','Submitted'),
  ('application_status','submitted','ru','Отклик'),
  ('application_status','submitted','he','נשלח'),
  ('application_status','viewed','tr','Görüldü'),
  ('application_status','viewed','en','Viewed'),
  ('application_status','viewed','ru','Просмотрено'),
  ('application_status','viewed','he','נצפה'),
  ('application_status','shortlisted','tr','Kısa liste'),
  ('application_status','shortlisted','en','Shortlisted'),
  ('application_status','shortlisted','ru','Шорт-лист'),
  ('application_status','shortlisted','he','ברשימה'),
  ('application_status','rejected','tr','Reddedildi'),
  ('application_status','rejected','en','Rejected'),
  ('application_status','rejected','ru','Отказ'),
  ('application_status','rejected','he','נדחה'),
  ('application_status','hired','tr','İşe alındı'),
  ('application_status','hired','en','Hired'),
  ('application_status','hired','ru','Нанят'),
  ('application_status','hired','he','גויס'),
  ('badge_type','email','tr','E-posta'),
  ('badge_type','email','en','Email'),
  ('badge_type','email','ru','Почта'),
  ('badge_type','email','he','אימייל'),
  ('badge_type','phone','tr','Telefon'),
  ('badge_type','phone','en','Phone'),
  ('badge_type','phone','ru','Телефон'),
  ('badge_type','phone','he','טלפון'),
  ('badge_type','company','tr','Şirket'),
  ('badge_type','company','en','Company'),
  ('badge_type','company','ru','Компания'),
  ('badge_type','company','he','חברה'),
  ('badge_type','identity','tr','Kimlik'),
  ('badge_type','identity','en','Identity'),
  ('badge_type','identity','ru','Личность'),
  ('badge_type','identity','he','זהות'),
  ('badge_status','pending','tr','Bekliyor'),
  ('badge_status','pending','en','Pending'),
  ('badge_status','pending','ru','Ожидание'),
  ('badge_status','pending','he','ממתין'),
  ('badge_status','verified','tr','Doğrulandı'),
  ('badge_status','verified','en','Verified'),
  ('badge_status','verified','ru','Подтверждено'),
  ('badge_status','verified','he','אומת'),
  ('badge_status','rejected','tr','Reddedildi'),
  ('badge_status','rejected','en','Rejected'),
  ('badge_status','rejected','ru','Отклонено'),
  ('badge_status','rejected','he','נדחה'),
  ('document_type','identity','tr','Kimlik belgesi'),
  ('document_type','identity','en','Identity document'),
  ('document_type','identity','ru','Документ личности'),
  ('document_type','identity','he','מסמך זהות'),
  ('document_type','tax_certificate','tr','Vergi belgesi'),
  ('document_type','tax_certificate','en','Tax certificate'),
  ('document_type','tax_certificate','ru','Налоговый сертификат'),
  ('document_type','tax_certificate','he','אישור מס'),
  ('document_type','other','tr','Diğer'),
  ('document_type','other','en','Other'),
  ('document_type','other','ru','Другое'),
  ('document_type','other','he','אחר'),
  ('document_status','pending','tr','Bekliyor'),
  ('document_status','pending','en','Pending'),
  ('document_status','pending','ru','Ожидание'),
  ('document_status','pending','he','ממתין'),
  ('document_status','verified','tr','Doğrulandı'),
  ('document_status','verified','en','Verified'),
  ('document_status','verified','ru','Подтверждено'),
  ('document_status','verified','he','אומת'),
  ('document_status','rejected','tr','Reddedildi'),
  ('document_status','rejected','en','Rejected'),
  ('document_status','rejected','ru','Отклонено'),
  ('document_status','rejected','he','נדחה'),
  ('cv_status','processing','tr','İşleniyor'),
  ('cv_status','processing','en','Processing'),
  ('cv_status','processing','ru','Обработка'),
  ('cv_status','processing','he','מעבד'),
  ('cv_status','ready','tr','Hazır'),
  ('cv_status','ready','en','Ready'),
  ('cv_status','ready','ru','Готово'),
  ('cv_status','ready','he','מוכן'),
  ('cv_status','failed','tr','Başarısız'),
  ('cv_status','failed','en','Failed'),
  ('cv_status','failed','ru','Ошибка'),
  ('cv_status','failed','he','נכשל'),
  ('outbox_status','pending','tr','Bekliyor'),
  ('outbox_status','pending','en','Pending'),
  ('outbox_status','pending','ru','Ожидание'),
  ('outbox_status','pending','he','ממתין'),
  ('outbox_status','processing','tr','İşleniyor'),
  ('outbox_status','processing','en','Processing'),
  ('outbox_status','processing','ru','Обработка'),
  ('outbox_status','processing','he','מעבד'),
  ('outbox_status','published','tr','Yayınlandı'),
  ('outbox_status','published','en','Published'),
  ('outbox_status','published','ru','Опубликовано'),
  ('outbox_status','published','he','פורסם'),
  ('outbox_status','failed','tr','Başarısız'),
  ('outbox_status','failed','en','Failed'),
  ('outbox_status','failed','ru','Ошибка'),
  ('outbox_status','failed','he','נכשל'),
  ('content_source','manual','tr','Elle'),
  ('content_source','manual','en','Manual'),
  ('content_source','manual','ru','Вручную'),
  ('content_source','manual','he','ידני'),
  ('content_source','ai_extracted','tr','AI çıkarımı'),
  ('content_source','ai_extracted','en','AI extracted'),
  ('content_source','ai_extracted','ru','Извлечено ИИ'),
  ('content_source','ai_extracted','he','חולץ ב-AI'),
  ('skill_proficiency','beginner','tr','Başlangıç'),
  ('skill_proficiency','beginner','en','Beginner'),
  ('skill_proficiency','beginner','ru','Начальный'),
  ('skill_proficiency','beginner','he','מתחיל'),
  ('skill_proficiency','intermediate','tr','Orta'),
  ('skill_proficiency','intermediate','en','Intermediate'),
  ('skill_proficiency','intermediate','ru','Средний'),
  ('skill_proficiency','intermediate','he','ביניים'),
  ('skill_proficiency','advanced','tr','İleri'),
  ('skill_proficiency','advanced','en','Advanced'),
  ('skill_proficiency','advanced','ru','Продвинутый'),
  ('skill_proficiency','advanced','he','מתקדם'),
  ('skill_proficiency','expert','tr','Uzman'),
  ('skill_proficiency','expert','en','Expert'),
  ('skill_proficiency','expert','ru','Эксперт'),
  ('skill_proficiency','expert','he','מומחה')
on conflict do nothing;

insert into public.regions (slug) values
  ('lefkosa'),
  ('girne'),
  ('gazimagusa'),
  ('guzelyurt'),
  ('iskele'),
  ('lefke')
on conflict (slug) do nothing;

insert into public.region_translations (region_id, locale, name)
select r.id, v.locale, v.name
from public.regions r
join (values
  ('lefkosa','tr','Lefkoşa'),
  ('lefkosa','en','Nicosia'),
  ('lefkosa','ru','Никосия'),
  ('lefkosa','he','ניקוסיה'),
  ('girne','tr','Girne'),
  ('girne','en','Kyrenia'),
  ('girne','ru','Кирения'),
  ('girne','he','קירניה'),
  ('gazimagusa','tr','Gazimağusa'),
  ('gazimagusa','en','Famagusta'),
  ('gazimagusa','ru','Фамагуста'),
  ('gazimagusa','he','פמגוסטה'),
  ('guzelyurt','tr','Güzelyurt'),
  ('guzelyurt','en','Morphou'),
  ('guzelyurt','ru','Морфу'),
  ('guzelyurt','he','מורפו'),
  ('iskele','tr','İskele'),
  ('iskele','en','Trikomo'),
  ('iskele','ru','Трикомо'),
  ('iskele','he','טריקומו'),
  ('lefke','tr','Lefke'),
  ('lefke','en','Lefka'),
  ('lefke','ru','Лефка'),
  ('lefke','he','לפקה')
) as v(slug, locale, name) on v.slug = r.slug
on conflict do nothing;

insert into public.cities (slug, region_id, sort_order)
select r.slug, r.id, r.id
from public.regions r
on conflict (slug) do nothing;

insert into public.city_translations (city_id, locale, name)
select c.id, rt.locale, rt.name
from public.cities c
join public.regions r on r.slug = c.slug
join public.region_translations rt on rt.region_id = r.id
on conflict do nothing;

insert into public.categories (slug, sort_order) values
  ('sales', 1),
  ('hospitality', 2),
  ('it', 3),
  ('construction', 4),
  ('education', 5),
  ('healthcare', 6),
  ('admin', 7),
  ('finance', 8),
  ('retail', 9),
  ('logistics', 10),
  ('legal', 11),
  ('other', 12)
on conflict (slug) do nothing;

insert into public.category_translations (category_id, locale, name)
select c.id, v.locale, v.name
from public.categories c
join (values
  ('sales','tr','Satış'),
  ('sales','en','Sales'),
  ('sales','ru','Продажи'),
  ('sales','he','מכירות'),
  ('hospitality','tr','Turizm ve otelcilik'),
  ('hospitality','en','Hospitality'),
  ('hospitality','ru','Гостиничный бизнес'),
  ('hospitality','he','אירוח'),
  ('it','tr','Bilişim'),
  ('it','en','IT'),
  ('it','ru','IT'),
  ('it','he','הייטק'),
  ('construction','tr','İnşaat'),
  ('construction','en','Construction'),
  ('construction','ru','Строительство'),
  ('construction','he','בנייה'),
  ('education','tr','Eğitim'),
  ('education','en','Education'),
  ('education','ru','Образование'),
  ('education','he','חינוך'),
  ('healthcare','tr','Sağlık'),
  ('healthcare','en','Healthcare'),
  ('healthcare','ru','Здравоохранение'),
  ('healthcare','he','בריאות'),
  ('admin','tr','Ofis ve idari'),
  ('admin','en','Admin'),
  ('admin','ru','Администрация'),
  ('admin','he','מנהלה'),
  ('finance','tr','Muhasebe ve finans'),
  ('finance','en','Finance'),
  ('finance','ru','Финансы'),
  ('finance','he','כספים'),
  ('retail','tr','Perakende'),
  ('retail','en','Retail'),
  ('retail','ru','Розничная торговля'),
  ('retail','he','קמעונאות'),
  ('logistics','tr','Lojistik'),
  ('logistics','en','Logistics'),
  ('logistics','ru','Логистика'),
  ('logistics','he','לוגיסטיקה'),
  ('legal','tr','Hukuk'),
  ('legal','en','Legal'),
  ('legal','ru','Юриспруденция'),
  ('legal','he','משפטים'),
  ('other','tr','Diğer'),
  ('other','en','Other'),
  ('other','ru','Другое'),
  ('other','he','אחר')
) as v(slug, locale, name) on v.slug = c.slug
on conflict do nothing;

insert into public.skills (slug) values
  ('turkish'),
  ('english'),
  ('russian'),
  ('greek'),
  ('excel'),
  ('customer-service'),
  ('sales'),
  ('driving-license')
on conflict (slug) do nothing;

insert into public.skill_translations (skill_id, locale, name)
select s.id, v.locale, v.name
from public.skills s
join (values
  ('turkish','tr','Türkçe'),
  ('turkish','en','Turkish'),
  ('turkish','ru','Турецкий'),
  ('turkish','he','טורקית'),
  ('english','tr','İngilizce'),
  ('english','en','English'),
  ('english','ru','Английский'),
  ('english','he','אנגלית'),
  ('russian','tr','Rusça'),
  ('russian','en','Russian'),
  ('russian','ru','Русский'),
  ('russian','he','רוסית'),
  ('greek','tr','Yunanca'),
  ('greek','en','Greek'),
  ('greek','ru','Греческий'),
  ('greek','he','יוונית'),
  ('excel','tr','Excel'),
  ('excel','en','Excel'),
  ('excel','ru','Excel'),
  ('excel','he','Excel'),
  ('customer-service','tr','Müşteri hizmetleri'),
  ('customer-service','en','Customer service'),
  ('customer-service','ru','Обслуживание клиентов'),
  ('customer-service','he','שירות לקוחות'),
  ('sales','tr','Satış'),
  ('sales','en','Sales'),
  ('sales','ru','Продажи'),
  ('sales','he','מכירות'),
  ('driving-license','tr','Ehliyet'),
  ('driving-license','en','Driving licence'),
  ('driving-license','ru','Водительские права'),
  ('driving-license','he','רישיון נהיגה')
) as v(slug, locale, name) on v.slug = s.slug
on conflict do nothing;
